#!/usr/bin/env bash
#task11
#shellcheck disable=SC2034
while IFS=: read -r username password uid gid fullname homedir shell; do
    echo "The user $username is part of the $gid gang, lives in $homedir and rides $shell."
    echo "USER ID's place is protected by the passcode $password, more info about the user here: $fullname"
done < /etc/passwd
