#!/usr/bin/env bash
#task6
#shellcheck disable=SC2034
hour=0
while [ $hour -le 12 ]; do
   minute=1
   echo "Hour: $hour"
   while [ $minute -lt 60 ]; do
      echo "$minute"
      ((minute++))
   done
   ((hour++))
done | timeout 30 head -n 70
