#!/usr/bin/env bash
#task3
#shellcheck disable=SC2034
for pid in /proc/[0-9]*; do
    pid_num=$(basename "$pid")
    if [[ -r "$pid/comm" ]]; then
        proc_name=$(cat "$pid/comm")
        if [[ "$proc_name" == *bash* ]]; then
            echo "$pid_num $proc_name"
        fi
    fi
done
